### ISSUE TITLE
Violating playsound's MIT License

### ISSUE THREAD

**Issue by TaylorSMarks** [mixmastamyk/boombox#4]
Hello,

I released playsound under the extremely permissive MIT License.

It has only a single requirement, which is that you leave the license intact.

By forking playsound, removing the MIT License and inserting the LGPL License in its place, you've violated the MIT License. Please put the MIT License back so you're in compliance with it again. You could probably somehow separate out your changes and apply LGPL to just those parts and be in compliance with it, if it's important to you.

(Unless I'm wrong and this isn't a fork? Github doesn't call it such, but I think you've told me that you forked playsound for this project before.)

**Comment by mixmastamyk** [comment]
I didn't fork it no... but it's possible I copied some code.  But I did a heavy refactor at some point too.  Does it still have any similarities?  Honestly can't remember as I've not touched this thing in a long time.

I have some time off soon and will investigate.

**Comment by mixmastamyk** [comment]
Sorry no.  Believe originally I'd planned to fork it, but it was very short, then later found a better abstraction.  So, I decided to rewrite it from the ground up the way I preferred in a few hours.

The thread says as much:
https://github.com/TaylorSMarks/playsound/issues/42

There's probably a few similarities in calling external audio libraries but that's determined by their interfaces, not us.
